services:
  - type: web
    name: retinal-oct-analyzer
    env: python
    plan: free   # upgrade to 'starter' or higher if you need more resources
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run your_file_name.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "true"

